### ISSUE TITLE
get session data?

### ISSUE THREAD

**Issue by justekoro** [ducktors/fastify-socket.io#10]
hi,
when using both fastify-socket.io and fastify-session, is there a way to get session data when socket client connects?
something like this would be cool:
![image](https://user-images.githubusercontent.com/35098503/126813074-e52d9be1-961a-4073-9ced-bed68bf9270d.png)

**Comment by justekoro** [comment]
solved! here is the code I used:
```app.listen(3821).then(()=>{
    app.io.on('connect', (socket) => {
        console.info('socket connected:',socket.id);
        let sid = app.parseCookie(socket.handshake.headers.cookie).sessionId;
        let req = {};
        app.decryptSession(sid, req, () => {
            console.log(req.session)
            // You can basically access req.session here
        });
    })
})
```

**Comment by alemagio** [comment]
@korobaka thanks for sharing the solution!

**Comment by justekoro** [comment]
> @korobaka thanks for sharing the solution!

no problem! it would be cool to include directly socket.session in this module :)

**Comment by alemagio** [comment]
feel free to open a PR, I'll be more than happy to review 😄

**Comment by justekoro** [comment]
> feel free to open a PR, I'll be more than happy to review 😄

I'll try to do this today :)
