### ISSUE TITLE
how to pass options to socket.io

### ISSUE THREAD

**Issue by outranker** [ducktors/fastify-socket.io#12]
I am registering this package as a plugin but i also need to pass some options to configure socket.io.
I don't see any example about how to do it. 
When I try adding it by myself I get a lot of Typescript errors.
Is there any way to pass options to socket.io?

**Comment by outranker** [comment]
Oh, the example was right there in Usage section 🤦🤦🤦
I apologize for my carelessness

Closing the issue

**Comment by alemagio** [comment]
No problem @outranker 
Let me know if you have any issue and if you thing something is missing in the doc feel free to open a PR 😜
