### ISSUE TITLE
property remoteJoin doesn't exist when using @socket.io/redis-adapter

### ISSUE THREAD

**Issue by outranker** [ducktors/fastify-socket.io#13]
When i added redis-adapter to socket.io typescript throws an error saying remoteJoin doesn't exist on type
This is the error:
```
TS2339: Property 'remoteJoin' does not exist on type 
'{ (): typeof Adapter | ((nsp: Namespace<DefaultEventsMap, 
DefaultEventsMap, DefaultEventsMap>) => Adapter) | undefined; 
(v: AdapterConstructor): Server<...>; }'.

           fastify.io.adapter.remoteJoin(
```

this is how my plugin looks like:
```
import fp from "fastify-plugin";
import { FastifyInstance } from "fastify";
import sio from "fastify-socket.io";
import { createAdapter } from "@socket.io/redis-adapter";
import redis from "../lib/redis-connection";
async function socketio(fastify: FastifyInstance) {
  fastify
    .register(sio, {
      transports: ["websocket"],
      maxHttpBufferSize: 50e9,
      cors: {
        origin: "*",
      },
    })
    .ready((err) => {
      if (err) throw err;

      fastify.io.adapter(createAdapter(redis.pubClient, redis.subClient));
    });
}

export default fp(socketio);
```

and this is how my redis adapter setup looks like (`redis-connection.ts` file):
```
import { RedisClient } from "redis";

const client = new RedisClient({
  host: process.env.REDIS_HOST,
  port: Number(process.env.REDIS_PORT),
  db: Number(process.env.REDIS_DB),
  password: process.env.REDIS_PASS,
});
const pubClient = client.duplicate();

const subClient = client.duplicate();


export default {
  pubClient,
  subClient,
};
```

and this is how i am registering `fastify-socket.io` as a plugin in my `server.ts` file

```
fastify.register(socketioPlugin).after(() => {
  console.log("socket.io plugin loaded");
});
```

any idea how i can fix this type error?

**Comment by alemagio** [comment]
Hi, did you follow these steps, including the installation of redis types? https://socket.io/docs/v4/redis-adapter/#installation

**Comment by outranker** [comment]
Yes, i did follow those steps and `@types/redis` is installed as well

**Comment by alemagio** [comment]
@outranker 
I tried some stuff but the problem is that socket.io returns the adapter with type `Adapter`, I could not find a solution for that but I'm afraid is not related to the plugin itself I think you would have the same issue using socket.io directly.

**Comment by outranker** [comment]
@alemagio 
yes, i tried to do the same using `socket.io` instead of `fastify-socket.io` but to no avail. i guess my TS knowledge is not sufficient enough to solve this. i will try to seek help from forums or some other place. thank you very much for your response
