### ISSUE TITLE
The onClose hooks are not triggered when there is active websocket connection

### ISSUE THREAD

**Issue by ud-klee** [ducktors/fastify-socket.io#16]
Hi, I found that the `onClose` hook blocks server shutdown until all clients disconnect. How to override the default behavior and forcibly kill all client connections (like using `io.disconnectSockets(true)`)?

**Comment by ud-klee** [comment]
Ok now I get that it's not the `onClose` hook blocking, actually the close event is stuck somewhere when at least one client has established the websocket connection. None of the `onClose` hook is triggered until I kill one of WS client.

**Comment by alemagio** [comment]
Hi @ud-klee 
can you provide some info to reproduce this?

**Comment by ud-klee** [comment]
Here's a minimal project I used for testing. Run `npm start` to launch the server. If I open "http://localhost:3000" and press Ctrl-C in the console, it will stuck after printing `SIGINT`. If I then refresh the browser window, the server will continue the shutdown sequence.

I'm using node v16.13 on Ubuntu 20.04.3.

```javascript
// server.js
const fastify = require('fastify')({ logger: true })
const path = require('path')
const io = require('socket.io')(fastify.server)

io.on('connect', socket => {
  console.log(`${socket.id} connected`)
  socket.on('disconnect', () => {
    console.log(`${socket.id} disconnected`)
  })
})

fastify.register(require('fastify-static'), { root: path.join(__dirname, './public') })
fastify.addHook('onClose', async () => {
  console.log(`fastify closing`)
})

process.once('SIGINT', (signal) => {
  console.log(`${signal}`)
  fastify.close(() => {
    console.log(`fastify closed`)
  })
})

fastify.listen(3000)

```

```html
// public/index.html
<!DOCTYPE html>
<html>
<head>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.socket.io/4.3.2/socket.io.min.js" integrity="sha384-KAZ4DtjNhLChOB/hxXuKqhMLYvx3b5MlT55xPEiNmREKRzeEm+RVPlTnAn0ajQNs" crossorigin="anonymous"></script>
  <script>
    $(function() {
      const socket = io()
      socket.on('connect', () => {
        console.log('ws ready')
      })
      socket.on('disconnect', reason => {
        console.log(`ws disconnected. reason = ${reason}`)
      })
    })
  </script>
</head>
<body></body>
</html>

```

```javascript
// package.json
{
  "name": "fastify",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "start": "node server.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "fastify": "^3.24.0",
    "fastify-static": "^4.5.0",
    "socket.io": "^4.4.0"
  }
}

```


I debugged the server and found that it appears to have blocked at the `instance.server.close(done)` call in `fastify.js` around line 376:

```javascript
  // cache the closing value, since we are checking it in an hot path
  avvio.once('preReady', () => {
    fastify.onClose((instance, done) => {
      fastify[kState].closing = true
      router.closeRoutes()
      if (fastify[kState].listening) {
        // No new TCP connections are accepted
        instance.server.close(done)
      } else {
        done(null)
      }
    })
  })

```

**Comment by alemagio** [comment]
@ud-klee 
I'm seeing your code and I don't see where you used the `fastify-socket.io` plugin.
I think your problem is that you are using `socket.io` in a `fastify` project but when you try to close the server it remains open waiting for the socket connection to be closed.
This is something that should be handled if you use this plugin.

Please let me know if there is something I am missing or if you need any help with the configuration.
