### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by flav-code** [ducktors/fastify-socket.io#18]
Hello your plugin don't work with me
![image](https://user-images.githubusercontent.com/48295189/156464251-9f9d2ca2-3f71-42a3-8d90-ac27050d4ff6.png)

**Comment by alemagio** [comment]
Hi
can you provide a bit more context?
The error log for example.

**Comment by flav-code** [comment]
I don't have error, i use vuejs for my front

**Comment by flav-code** [comment]
I think the socket is not listening to the fastify port
