### ISSUE TITLE
Why do i get "closed incoming websocket connection"

### ISSUE THREAD

**Issue by nezts08** [ducktors/fastify-socket.io#19]
when i try to connect via socket-io i get this error:

![image](https://user-images.githubusercontent.com/68449193/168494052-f5a8d478-3979-4c3a-a403-198bac6d68f4.png)

nothing appears in postman:

![image](https://user-images.githubusercontent.com/68449193/168494108-dc1bd069-1e7a-4c01-81d3-9d03b7ebdda8.png)

code: https://github.com/SKrind0/fastifyWebsocket-error/tree/19942147c88a177e4d8fd28c43fa41872765e3ba

**Comment by nezts08** [comment]
I already solved the problem (I think the problem was with another fastify plugin called fastify-websocket)

**Comment by trim21** [comment]
solution for who encounter same problme: remove `@fastify/websocket`

**Comment by trim21** [comment]
solution for who encounter same problme: remove `@fastify/websocket`
