### ISSUE TITLE
Support Fastify 4x

### ISSUE THREAD

**Issue by JoaoOtavioS** [ducktors/fastify-socket.io#21]
throw new FST_ERR_PLUGIN_VERSION_MISMATCH(meta.name, requiredVersion, this.version)

FastifyError [Error]: fastify-plugin: index-auto-0 - expected '3.x' fastify version, '4.0.0' is installed

**Comment by JoaoOtavioS** [comment]
https://github.com/alemagio/fastify-socket.io/pull/22

**Comment by JoaoOtavioS** [comment]
https://github.com/alemagio/fastify-socket.io/pull/23

**Comment by neckaros** [comment]
I think doc should be updated too ?
`Supports Fastify versions 3.x`
i can do a quick PR if it helps
