### ISSUE TITLE
cant run package in fastify 4.0.3

### ISSUE THREAD

**Issue by michelwaechter** [ducktors/fastify-socket.io#25]
Hello there.

Thanks four your work and this package.. I'm not able to start the fastify-server with the package.. and i cant find an workaround for version 3.. got this error:

`"message":"fastify-plugin: index-auto-0 - expected '3.x' fastify version, '4.0.3' is installed","stack":"FastifyError: fastify-plugin: index-auto-0 - expected '3.x' fastify version, '4.0.3' is installed\n    at Object.checkVersion (......node_modules/fastify/lib/pluginUtils.js:118:11)\n    at Object.registerPlugin (.....node_modules/fastify/lib/pluginUtils.js:133:16)\n    at Boot.override (......node_modules/fastify/lib/pluginOverride.js:28:57)\n    at Plugin.exec (......node_modules/avvio/plugin.js:80:33)\n    at Boot.loadPlugin (......node_modules/avvio/plugin.js:273:10)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","name":"FastifyError","code":"FST_ERR_PLUGIN_VERSION_MISMATCH","statusCode":500},"msg":"fastify-plugin: index-auto-0 - expected '3.x' fastify version, '4.0.3' is installed"}`

Can you help me or give me any workaround?

**Comment by JoaoOtavioS** [comment]
hey friend, just wait https://github.com/alemagio/fastify-socket.io/pull/23
I think the release should come out soon, since the pull is already ok

**Comment by YuriFontella** [comment]
Has this been fixed yet?

I changed the 3.x to 4.x directly in the index file in node_modules, just to run the project without errors. But I don't know if this can have any negative effect on the functioning.

**Comment by JoaoOtavioS** [comment]
I don't think so, but just switch 3.x to 4.x and it works fine, no problems

**Comment by alemagio** [comment]
I just release v4 of the plugin, it should support both fastify v3 (latest) and v4

**Comment by JoaoOtavioS** [comment]
good job @alemagio, thanks for the support community <3

**Comment by lemanh2006** [comment]
when I switch to 4.x. I have error cannot connect to socket.io. anyone can help me ? thanks

This is example

index.js
```
const fastify = require('fastify')
const socketio = require('fastify-socket.io')
const { join } = require('path')
const { readFile } = require('fs').promises

const app = fastify({ logger: true })

app.register(socketio)

app.get('/', async (req, reply) => {
  const data = await readFile(join(__dirname, 'index.html'))
  reply.header('content-type', 'text/html; charset=utf-8')
  reply.send(data)
})

app.ready(err => {
  if (err) throw err

  app.io.on('connect', (socket) => console.info('Socket connected!', socket.id))
})

app.listen(3000)
```

**Comment by alemagio** [comment]
@lemanh2006 
can you share the error log and possibly an example (client included) to reproduce the error?

**Comment by lemanh2006** [comment]
Hi @alemagio , I have same error with this guys https://github.com/alemagio/fastify-socket.io/issues/27
