### ISSUE TITLE
Authentication Documentation

### ISSUE THREAD

**Issue by amyadamslou** [ducktors/fastify-socket.io#29]
Hello! First off, thank you so much for this plugin with Fastify. I'm trying to establish authentication with socket connections using fastifyPassport and fastifySessions. Are there any documents on it for doing it the right way?

**Comment by amyadamslou** [comment]
[10](https://github.com/alemagio/fastify-socket.io/issues/10)

is there a way to obtain this easier from the socket object, like wrapping as a middleware?

**Comment by HsinHeng** [comment]
> [10](https://github.com/alemagio/fastify-socket.io/issues/10)
> 
> is there a way to obtain this easier from the socket object, like wrapping as a middleware?

if I use fastify-passport & fastify-secure-session, how to decrypt session?

**Comment by alemagio** [comment]
Hey
At the moment the only thing provided by the plugin is a decorator which contains the `io` object.
If you would like to have something like that maybe you can open a PR and we can discuss about that
