### ISSUE TITLE
Typescript example not working

### ISSUE THREAD

**Issue by mricharz** [ducktors/fastify-socket.io#3]
Hi there

I don't get anything to work.

```
Node 12.8.1
fastify 3.9.1
fastify-socket.io 1.0.1
```

If i just copy [your example](https://github.com/alemagio/fastify-socket.io/blob/master/examples/typescript/server.ts) 1:1 and correct the import to `'fastify-socket.io'`:

`Server listening at http://127.0.0.1:3000` the server starts.

But if i then try to connect to the websocket with
1. my client on ws://127.0.0.1:3000
2. or with [Websocket Tester](https://www.websocket.org/echo.html) on ws://127.0.0.1:3000

nothing works. No success. No error. Nothing at all.

Also i am able to access the fastify server on port 3000. ergo no firewall problem.

The documentation is very small and frustrating. Please help.

**Comment by alemagio** [comment]
Hi, while running the example if you visit http://locahost:3000/ you should see a message and in the fastify log you should see `Socket connected`.
It is a very basic example but if you have experience using socket.io you can just use `fastify.io` decorator exactly as if you were using the socketio instance.

Hope this will help but if you still have questions don't hesitate to ask :smiley:

**Comment by mricharz** [comment]
Ok that is gross. Looks like Socket.io is not a normal socket-server.
It connects to /socket.io instead of just /. I don't know what magic is happening behind this monster but...
This is a thing that should be marked in **fat** **red** letters on the github socket.io page at the first line.

nerverless...
after finding this out i got cors problems while connecting to the socket server.
my app is running on port 3006 and tries to connect to localhost:3000  to socket.io.
i got fastify-cors registred but it seems socket.io is just ignoring this cors-plugin.

some googleing and i found out that socket.io has its own cors-functionality.
Thanks for your time and help. I got it working for now. but i think i will switch away from socket.io.
i'm wasting more time in figuring stuff out with socket.io than just going forward with basic websocket knowledge.

this can be closed. :-)

**Comment by alemagio** [comment]
Yeah well happy to have been helpful.
I also configured my nginx to fit the /socket.io/ url.
Maybe I should also include that in a more detailed example.
Thanks for your explanation too.
