### ISSUE TITLE
should we use this plugin? what to use instead?

### ISSUE THREAD

**Issue by ghost** [ducktors/fastify-socket.io#32]
Hello, I am new to Fastify and wanted to use socket.io. I see this library is no longer maintained. Could you please tell me what I should use instead to connect fastify and socket.io?

**Comment by alemagio** [comment]
Hi @terlan4 
the plugin is maintained, there is some work that should be done to update some things but I could not work actively on it

Anyway, i f you prefer to copy the code or fork it go for it 😄 
The code is very simple

**Comment by terlan4** [comment]
@alemagio I asked because Readme file says that it supports fastify 3.x. Anyways, happy to hear the opposite :)
Could you please tell me if it is possible to use all functionalities of socket.io without limitations in fastify?
(I am sorry for such a noob question)

**Comment by alemagio** [comment]
fastify and socket.io are unrelated 
you can use it with no limitations, this plugin will be updated to support fastify v4
there is a PR open

**Comment by terlan4** [comment]
Thank you very much for fast response :)
