### ISSUE TITLE
Sockets handler events

### ISSUE THREAD

**Issue by i-montes** [ducktors/fastify-socket.io#35]
is it necessary for the events to be inside the coonnection handler? i have been testing with events outside the 'connection' event and it does not work.

```
  fastify.io.on("connection", (socket) => {
    // Work 
    socket.on("test", (msg:any) => {
      console.log("test: ", msg);
    });
  });

  // Not work
  fastify.io.on("chat message", (msg) => {
    fastify.io.emit("chat message", msg);
  });
```

**Comment by alemagio** [comment]
Hi, I am afraid this is related to `socket.io` itself not this plugin.
