### ISSUE TITLE
bug when installing (using yarn)

### ISSUE THREAD

**Issue by musabkhunaijir** [ducktors/fastify-socket.io#4]
> node_modules/fastify-socket.io/index.d.ts:6:9 - error TS2503: Cannot find namespace 'SocketIO'.
     io: SocketIO.Server

**Comment by alemagio** [comment]
Hi, could you provide a bit more info?
Are you using typescript?
Node and Fastify version?
Last version of the plugin?

**Comment by musabkhunaijir** [comment]
ok for sure :

> "fastify": "3.5.1",
> node v14.15.1
> yes it was the latest one

**Comment by alemagio** [comment]
@musabkhunaijir 
Typescript right?

**Comment by musabkhunaijir** [comment]
> @musabkhunaijir
> Typescript right?

yet it's typescript:
> Version 4.1.2

**Comment by alemagio** [comment]
@musabkhunaijir 
I think you are missing `yarn add -D @types/socket.io`.
Is that possible?

**Comment by Windrushfarer** [comment]
Have same issue, your workaround not working

**Comment by musabkhunaijir** [comment]
> Have same issue, your workaround not working

my issue was that I had a folder named as the same GraphQLnode module one and the conflict happened

**Comment by alemagio** [comment]
> my issue was that I had a folder named as the same GraphQLnode module one and the conflict happened

thanks for clarifying that @musabkhunaijir
