### ISSUE TITLE
Release notes for v5?

### ISSUE THREAD

**Issue by MariuzM** [ducktors/fastify-socket.io#43]
Hello, is there any release notes for V5, i have tried updating but broke everything, will check later what was the issue.

**Comment by MariuzM** [comment]
Update, something maybe was off with my packages i had others updated, working fine now, still curious to see release notes

**Comment by alemagio** [comment]
HI @MariuzM 
Yes, I changed the release workflow and doing that we missed the release notes
For this release I added it manually.
