### ISSUE TITLE
Socket IO 4

### ISSUE THREAD

**Issue by ilteoood** [ducktors/fastify-socket.io#6]
Hi,
do you have any plan to upgrade it to socket io 4?

**Comment by alemagio** [comment]
Hi @ilteoood 
For sure, I haven't had so much time these days but I will definitely want to update.
Also feel free to open a PR and update it, I will be more than happy to have contributors :smiley:

**Comment by alemagio** [comment]
With v2.0.0 we have Socketio v4 :partying_face:
